services:
  - type: web
    name: glowtime
    env: php
    plan: free
    region: oregon

    buildCommand: "./build.sh"
    startCommand: "php artisan serve --host 0.0.0.0 --port $PORT"

    envVars:
      - key: APP_ENV
        value: production

      - key: APP_KEY
        sync: false

      - key: APP_DEBUG
        value: false

      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: ${MYSQL_HOST}
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: ${MYSQL_DATABASE}
      - key: DB_USERNAME
        value: ${MYSQL_USER}
      - key: DB_PASSWORD
        value: ${MYSQL_PASSWORD}
